version: "3"
services:
  db:
    build: "./Neo4j"
    ports:
      - "7474:7474"
      - "7687:7687"
  testdb:
    build: "./Neo4j"
    ports:
      - "7475:7474"
      - "7688:7687"
  web:
    build: .
    depends_on:
      - "db"
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    links:
      - db:db
      - testdb:testdb
